package app.olsaathi.content

import android.content.Context
import org.json.JSONObject
import java.util.Locale

/**
 * Loads and queries the pre-translated content pack.
 *
 * The pack is generated by tools/build_pack.mjs and shipped inside the
 * APK as assets/pack/pack.sat.json. Every entry records which Bhashini
 * service produced it, so provenance is in the data.
 *
 * Lookup order:
 *   1. Exact match on source text (trimmed)
 *   2. Normalised match (trim, collapse whitespace, strip trailing ।.?!)
 *   3. UNAVAILABLE
 *
 * N1: There is no generic fallback phrase. A miss returns an empty
 * target with provenance UNAVAILABLE.
 */
class VerifiedContentPack private constructor() {

    data class PackEntry(
        val id: String,
        val source: String,
        val target: String,
        val en: String,
        val nipun: String,
        val kind: String,
        val service: String,
        val audio: String?,
        val lesson: String?,
        /** Set by apply_review.py when a Santali speaker reviews this entry. */
        val reviewedBy: String = "",
        val reviewedOn: String = "",
        val reviewVerdict: String = "",
    )

    // Visible for testing
    /**
     * True when this pack is placeholder content rather than Bhashini output.
     * Every lookup is then downgraded from VERIFIED to SAMPLE, so the app
     * physically cannot present invented Santali as a real translation.
     */
    var isSample: Boolean = false
        private set

    internal val entries = mutableMapOf<String, PackEntry>()
    private val normalisedIndex = mutableMapOf<String, PackEntry>()

    /** Provenance metadata from the pack header. */
    var translationService: String = ""
        private set
    var ttsService: String = ""
        private set
    var platform: String = ""
        private set
    var pivot: String = ""
        private set
    var generated: String = ""
        private set

    /** Human review metadata from the pack header. Null when no review has happened. */
    var humanReview: HumanReview? = null
        private set

    data class HumanReview(
        val reviewer: String,
        val background: String,
        val date: String,
        val confirmed: Int,
        val corrected: Int,
        val removed: Int,
        val unreviewed: Int,
    )

    /** Number of entries loaded. */
    val size: Int get() = entries.size

    /** Number of entries that have been human-reviewed. */
    val reviewedCount: Int get() =
        entries.values.count { it.reviewedBy.isNotEmpty() && it.reviewVerdict in listOf("confirmed", "corrected") }

    /**
     * Look up by Hindi source text.
     * Returns [Translation] with appropriate provenance.
     */
    fun lookup(hindi: String): Translation {
        val trimmed = hindi.trim()
        if (trimmed.isEmpty()) {
            return Translation(
                source = hindi,
                target = "",
                en = "",
                provenance = Provenance.UNAVAILABLE
            )
        }

        // 1. Exact match
        entries[normaliseKey(trimmed)]?.let { entry ->
            return entryToTranslation(entry, hindi)
        }

        // 2. Normalised match
        val norm = normalise(trimmed)
        normalisedIndex[norm]?.let { entry ->
            return entryToTranslation(entry, hindi)
        }

        // 3. UNAVAILABLE — N1: no fallback, no guess
        return Translation(
            source = hindi,
            target = "",
            en = "",
            provenance = Provenance.UNAVAILABLE
        )
    }

    /**
     * Convert a PackEntry to a Translation, choosing the right provenance.
     *
     * HUMAN_VERIFIED takes precedence over VERIFIED/SAMPLE — if someone
     * reviewed it, that is the strongest claim we make for that entry.
     */
    private fun entryToTranslation(entry: PackEntry, fallbackSource: String): Translation {
        // Determine provenance: HUMAN_VERIFIED > SAMPLE > VERIFIED
        val provenance = when {
            entry.reviewedBy.isNotEmpty() && entry.reviewVerdict in listOf("confirmed", "corrected") ->
                Provenance.HUMAN_VERIFIED
            isSample -> Provenance.SAMPLE
            else -> Provenance.VERIFIED
        }

        return Translation(
            source = entry.source.ifEmpty { fallbackSource },
            target = entry.target,
            en = entry.en,
            provenance = provenance,
            serviceId = entry.service,
            entryId = entry.id,
            nipun = entry.nipun,
            kind = entry.kind,
            reviewerName = entry.reviewedBy,
            reviewedOn = entry.reviewedOn,
        )
    }

    /** Get the audio asset path for a translation, or null. */
    fun audioPath(translation: Translation): String? {
        return entries[translation.entryId]?.audio
    }

    /** Get all entries, optionally filtered by lesson id. */
    fun entries(lessonId: String? = null): List<PackEntry> {
        return if (lessonId != null) {
            entries.values.filter { it.lesson == lessonId || it.kind == "phrase" }
        } else {
            entries.values.toList()
        }
    }

    /** Get unique lesson IDs from lesson-type entries. */
    fun lessonIds(): List<String> {
        return entries.values
            .filter { it.lesson != null }
            .map { it.lesson!! }
            .distinct()
            .sorted()
    }

    companion object {
        private var instance: VerifiedContentPack? = null

        /** Load the pack from assets. Call once at app startup. */
        fun load(context: Context): VerifiedContentPack {
            instance?.let { return it }

            val pack = VerifiedContentPack()
            val json = context.assets.open("pack/pack.sat.json").bufferedReader(Charsets.UTF_8).use { it.readText() }
            val root = JSONObject(json)

            pack.generated = root.optString("generated", "")
            val prov = root.optJSONObject("provenance")
            // Any of these means the pack was not produced by a real Bhashini
            // run, so nothing in it may claim to be verified.
            pack.isSample = (prov?.optString("note") ?: "").contains("SAMPLE", ignoreCase = true) ||
                (prov?.optBoolean("sample") ?: false) ||
                (prov?.optString("translationService") ?: "").let { it.isEmpty() || !it.contains("/") || it == "ai4bharat/translation" }
            pack.translationService = prov?.optString("translationService", "") ?: ""
            pack.ttsService = prov?.optString("ttsService", "") ?: ""
            pack.platform = prov?.optString("platform", "") ?: ""
            pack.pivot = prov?.optString("pivot", "") ?: ""

            // Human review metadata (optional — absent when no review has happened)
            val hr = prov?.optJSONObject("humanReview")
            if (hr != null) {
                pack.humanReview = HumanReview(
                    reviewer = hr.optString("reviewer", ""),
                    background = hr.optString("background", ""),
                    date = hr.optString("date", ""),
                    confirmed = hr.optInt("confirmed", 0),
                    corrected = hr.optInt("corrected", 0),
                    removed = hr.optInt("removed", 0),
                    unreviewed = hr.optInt("unreviewed", 0),
                )
            }

            val entriesObj = root.optJSONObject("entries") ?: JSONObject()
            val keys = entriesObj.keys()
            while (keys.hasNext()) {
                val id = keys.next()
                val e = entriesObj.getJSONObject(id)
                val entry = parseEntry(id, e)
                pack.entries[normaliseKey(entry.source)] = entry
                // Build normalised index for fuzzy lookup
                val norm = normalise(entry.source)
                if (norm.isNotEmpty()) {
                    pack.normalisedIndex[norm] = entry
                }
            }

            instance = pack
            return pack
        }

        /** Visible for testing. */
        internal fun loadFromString(json: String): VerifiedContentPack {
            val pack = VerifiedContentPack()
            val root = JSONObject(json)
            pack.generated = root.optString("generated", "")
            val prov = root.optJSONObject("provenance")
            pack.isSample = (prov?.optString("note") ?: "").contains("SAMPLE", ignoreCase = true) ||
                (prov?.optBoolean("sample") ?: false) ||
                (prov?.optString("translationService") ?: "").let { it.isEmpty() || !it.contains("/") || it == "ai4bharat/translation" }
            pack.translationService = prov?.optString("translationService", "") ?: ""
            pack.ttsService = prov?.optString("ttsService", "") ?: ""
            pack.platform = prov?.optString("platform", "") ?: ""
            pack.pivot = prov?.optString("pivot", "") ?: ""

            val hr = prov?.optJSONObject("humanReview")
            if (hr != null) {
                pack.humanReview = HumanReview(
                    reviewer = hr.optString("reviewer", ""),
                    background = hr.optString("background", ""),
                    date = hr.optString("date", ""),
                    confirmed = hr.optInt("confirmed", 0),
                    corrected = hr.optInt("corrected", 0),
                    removed = hr.optInt("removed", 0),
                    unreviewed = hr.optInt("unreviewed", 0),
                )
            }

            val entriesObj = root.optJSONObject("entries") ?: JSONObject()
            val keys = entriesObj.keys()
            while (keys.hasNext()) {
                val id = keys.next()
                val e = entriesObj.getJSONObject(id)
                val entry = parseEntry(id, e)
                pack.entries[normaliseKey(entry.source)] = entry
                val norm = normalise(entry.source)
                if (norm.isNotEmpty()) {
                    pack.normalisedIndex[norm] = entry
                }
            }
            return pack
        }

        private fun parseEntry(id: String, e: JSONObject): PackEntry {
            return PackEntry(
                id = id,
                source = e.optString("source", ""),
                target = e.optString("target", ""),
                en = e.optString("en", ""),
                nipun = e.optString("nipun", ""),
                kind = e.optString("kind", ""),
                service = e.optString("service", ""),
                audio = e.optString("audio", "").ifEmpty { null },
                lesson = e.optString("lesson", "").ifEmpty { null },
                reviewedBy = e.optString("reviewedBy", ""),
                reviewedOn = e.optString("reviewedOn", ""),
                reviewVerdict = e.optString("reviewVerdict", ""),
            )
        }

        /**
         * Normalise a Hindi string for lookup.
         * Trim, collapse whitespace, strip trailing danda/punctuation.
         */
        fun normalise(text: String): String {
            return text.trim()
                .replace(Regex("\\s+"), " ")
                .replace(Regex("[।.?!]+$"), "")
                .trim()
        }

        private fun normaliseKey(text: String): String {
            return text.trim()
        }
    }
}
