package app.olsaathi.content

import android.content.Context
import org.json.JSONObject
import java.util.Locale

/**
 * Loads and queries the pre-translated content pack.
 *
 * The pack is generated by tools/build_pack.mjs and shipped inside the
 * APK as assets/pack/pack.sat.json. Every entry records which Bhashini
 * service produced it, so provenance is in the data.
 *
 * Lookup order:
 *   1. Exact match on source text (trimmed)
 *   2. Normalised match (trim, collapse whitespace, strip trailing ।.?!)
 *   3. UNAVAILABLE
 *
 * N1: There is no generic fallback phrase. A miss returns an empty
 * target with provenance UNAVAILABLE.
 */
class VerifiedContentPack private constructor() {

    data class PackEntry(
        val id: String,
        val source: String,
        val target: String,
        val en: String,
        val nipun: String,
        val nipunOutcome: String,
        val nipunGoal: String,
        val nipunDomain: String,
        val kind: String,
        val service: String,
        val audio: String?,
        val audioProvenance: String?,
        /** Drawable resource name for the card picture, e.g. "ic_card_p01". */
        val image: String?,
        val lesson: String?,
        /** Set by apply_review.py when a Santali speaker reviews this entry. */
        val reviewedBy: String = "",
        val reviewedOn: String = "",
        val reviewVerdict: String = "",
        val bridge: String = "",
        val bridgeProvenance: String = "",
    )

    // Visible for testing
    /**
     * True when this pack is placeholder content rather than Bhashini output.
     * Every lookup is then downgraded from VERIFIED to SAMPLE, so the app
     * physically cannot present invented Santali as a real translation.
     */
    var isSample: Boolean = false
        private set

    internal val entries = mutableMapOf<String, PackEntry>()
    private val normalisedIndex = mutableMapOf<String, PackEntry>()

    /**
     * Entries keyed by their pack id, e.g. "p01".
     *
     * [entries] is keyed by source text, so anything holding an entry id had
     * no way to get back to the entry. That is what made audioPath() always
     * return null.
     */
    private val byId = mutableMapOf<String, PackEntry>()

    /**
     * Which language this pack holds, e.g. "sat" or "mar".
     *
     * The app used to carry exactly one pack, so nothing needed to say which
     * language was on screen. With a dropdown it does: a worksheet generated
     * from the wrong pack is silently wrong, and the PDF has no other way to
     * label itself.
     */
    var languageCode: String = ""
        private set
    var languageEnglish: String = ""
        private set

    /** Script key, e.g. "Olck" or "Deva". Chooses the typeface for PDFs. */
    var script: String = ""
        private set

    /** Font asset this pack's script needs, e.g. "NotoSansOlChiki-Regular.ttf". */
    var font: String = ""
        private set

    /**
     * How strong the build-time script guard was. See [LanguageOption.guard].
     *
     * Carried into the app so the Check & Proof screen can distinguish a
     * language whose script proves it was translated from one that merely
     * looks plausible.
     */
    var guard: String = "strong"
        private set

    /** Provenance metadata from the pack header. */
    var translationService: String = ""
        private set
    var ttsService: String = ""
        private set
    var platform: String = ""
        private set
    var pivot: String = ""
        private set
    var generated: String = ""
        private set

    /**
     * The name to put on screen for whoever produced this Santali.
     *
     * Taken from the pack, never compiled in, so that replacing the content
     * replaces the label with it. The provenance block writes [platform] as a
     * sentence ("Bhashini (MeitY, Government of India)"), and only its opening
     * clause belongs on a 12sp chip, so that is what this trims to. Falls back
     * to the raw service id, and then to nothing at all: a pack that does not
     * say who made it gets a label that does not claim to know.
     */
    val serviceName: String
        get() {
            val fromPlatform = platform
                .substringBefore('(')
                .substringBefore(',')
                .substringBefore('.')
                .trim()
            return fromPlatform.ifEmpty { translationService }
        }

    /** Human review metadata from the pack header. Null when no review has happened. */
    var humanReview: HumanReview? = null
        private set

    data class HumanReview(
        val reviewer: String,
        val background: String,
        val date: String,
        val confirmed: Int,
        val corrected: Int,
        val removed: Int,
        val unreviewed: Int,
    )

    /** Number of entries loaded. */
    val size: Int get() = entries.size

    /** Number of entries that have been human-reviewed. */
    val reviewedCount: Int get() =
        entries.values.count { it.reviewedBy.isNotEmpty() && it.reviewVerdict in listOf("confirmed", "corrected") }

    /**
     * Look up by Hindi source text.
     * Returns [Translation] with appropriate provenance.
     */
    fun lookup(hindi: String): Translation {
        val trimmed = hindi.trim()
        if (trimmed.isEmpty()) {
            return Translation(
                source = hindi,
                target = "",
                en = "",
                provenance = Provenance.UNAVAILABLE
            )
        }

        // 1. Exact match
        entries[normaliseKey(trimmed)]?.let { entry ->
            return entryToTranslation(entry, hindi)
        }

        // 2. Normalised match
        val norm = normalise(trimmed)
        normalisedIndex[norm]?.let { entry ->
            return entryToTranslation(entry, hindi)
        }

        // 3. UNAVAILABLE — N1: no fallback, no guess
        return Translation(
            source = hindi,
            target = "",
            en = "",
            provenance = Provenance.UNAVAILABLE
        )
    }

    /**
     * Convert a PackEntry to a Translation, choosing the right provenance.
     *
     * HUMAN_VERIFIED takes precedence over VERIFIED/SAMPLE — if someone
     * reviewed it, that is the strongest claim we make for that entry.
     */
    private fun entryToTranslation(entry: PackEntry, fallbackSource: String): Translation {
        // Determine provenance: HUMAN_VERIFIED > SAMPLE > VERIFIED
        val provenance = when {
            entry.reviewedBy.isNotEmpty() && entry.reviewVerdict in listOf("confirmed", "corrected") ->
                Provenance.HUMAN_VERIFIED
            isSample -> Provenance.SAMPLE
            else -> Provenance.VERIFIED
        }

        return Translation(
            source = entry.source.ifEmpty { fallbackSource },
            target = entry.target,
            en = entry.en,
            provenance = provenance,
            serviceId = entry.service,
            serviceName = serviceName,
            entryId = entry.id,
            nipun = entry.nipun,
            nipunOutcome = entry.nipunOutcome,
            nipunGoal = entry.nipunGoal,
            nipunDomain = entry.nipunDomain,
            kind = entry.kind,
            audioAsset = entry.audio,
            audioProvenance = audioProvenanceOf(entry),
            reviewerName = entry.reviewedBy,
            reviewedOn = entry.reviewedOn,
            bridge = entry.bridge,
            bridgeProvenance = entry.bridgeProvenance,
        )
    }

    /** Get the audio asset path for a translation, or null. */
    fun audioPath(translation: Translation): String? {
        return byId[translation.entryId]?.audio
    }

    /** Number of entries that ship a recording. */
    val audioCount: Int get() = entries.values.count { !it.audio.isNullOrEmpty() }

    /**
     * Read the audio label off the entry.
     *
     * An entry with no audio is NONE regardless of what the field says, so a
     * stale label can never enable a play button that has nothing to play.
     */
    private fun audioProvenanceOf(entry: PackEntry): AudioProvenance {
        if (entry.audio.isNullOrEmpty()) return AudioProvenance.NONE
        return when (entry.audioProvenance) {
            "native" -> AudioProvenance.SPOKEN_BY_NATIVE
            "bhashini" -> AudioProvenance.BHASHINI_TTS
            "parler" -> AudioProvenance.PARLER_TTS
            else -> AudioProvenance.NONE
        }
    }

    /** Get all entries, optionally filtered by lesson id. */
    fun entries(lessonId: String? = null): List<PackEntry> {
        return if (lessonId != null) {
            entries.values.filter { it.lesson == lessonId || it.kind == "phrase" }
        } else {
            entries.values.toList()
        }
    }

    /** Get unique lesson IDs from lesson-type entries. */
    fun lessonIds(): List<String> {
        return entries.values
            .filter { it.lesson != null }
            .map { it.lesson!! }
            .distinct()
            .sorted()
    }

    companion object {
        /**
         * One loaded pack per language, kept for the life of the process.
         *
         * Switching language in the dropdown must not re-parse JSON every
         * time, and a teacher flipping between two languages mid-lesson is
         * the expected case rather than the rare one. Each pack is about
         * 33 KB of JSON, so holding several costs far less than the reparse.
         */
        private val cache = mutableMapOf<String, VerifiedContentPack>()

        /**
         * Load one language's pack from assets.
         *
         * Throws if the pack is missing. That is deliberate and matches the
         * original single-pack behaviour: a language offered by the manifest
         * but absent from assets is a build error, and failing loudly at the
         * moment of the switch beats a blank screen with no explanation.
         */
        fun load(context: Context, code: String = LanguageRegistry.FALLBACK_CODE): VerifiedContentPack {
            cache[code]?.let { return it }

            val pack = VerifiedContentPack()
            val json = context.assets.open("pack/pack.$code.json").bufferedReader(Charsets.UTF_8).use { it.readText() }
            val root = JSONObject(json)

            // Fall back to the requested code when the pack predates these
            // fields, so an older pack.sat.json still loads and labels itself.
            pack.languageCode = root.optString("language", code)
            pack.languageEnglish = root.optString("languageEnglish", "")
            pack.script = root.optString("script", "")
            pack.font = root.optString("font", "")
            pack.guard = root.optString("guard", "strong")
            pack.generated = root.optString("generated", "")
            val prov = root.optJSONObject("provenance")
            // Any of these means the pack was not produced by a real Bhashini
            // run, so nothing in it may claim to be verified.
            pack.isSample = (prov?.optString("note") ?: "").contains("SAMPLE", ignoreCase = true) ||
                (prov?.optBoolean("sample") ?: false) ||
                (prov?.optString("translationService") ?: "").let { it.isEmpty() || !it.contains("/") || it == "ai4bharat/translation" }
            pack.translationService = prov?.optString("translationService", "") ?: ""
            pack.ttsService = prov?.optString("ttsService", "") ?: ""
            pack.platform = prov?.optString("platform", "") ?: ""
            pack.pivot = prov?.optString("pivot", "") ?: ""

            // Human review metadata (optional — absent when no review has happened)
            val hr = prov?.optJSONObject("humanReview")
            if (hr != null) {
                pack.humanReview = HumanReview(
                    reviewer = hr.optString("reviewer", ""),
                    background = hr.optString("background", ""),
                    date = hr.optString("date", ""),
                    confirmed = hr.optInt("confirmed", 0),
                    corrected = hr.optInt("corrected", 0),
                    removed = hr.optInt("removed", 0),
                    unreviewed = hr.optInt("unreviewed", 0),
                )
            }

            val entriesObj = root.optJSONObject("entries") ?: JSONObject()
            val keys = entriesObj.keys()
            while (keys.hasNext()) {
                val id = keys.next()
                val e = entriesObj.getJSONObject(id)
                val entry = parseEntry(id, e)
                pack.entries[normaliseKey(entry.source)] = entry
                pack.byId[id] = entry
                // Build normalised index for fuzzy lookup
                val norm = normalise(entry.source)
                if (norm.isNotEmpty()) {
                    pack.normalisedIndex[norm] = entry
                }
            }

            cache[code] = pack
            return pack
        }

        /** Drop cached packs. Used by tests; the assets never change at runtime. */
        internal fun clearCache() {
            cache.clear()
        }

        /** Visible for testing. */
        internal fun loadFromString(json: String): VerifiedContentPack {
            val pack = VerifiedContentPack()
            val root = JSONObject(json)
            pack.generated = root.optString("generated", "")
            val prov = root.optJSONObject("provenance")
            pack.isSample = (prov?.optString("note") ?: "").contains("SAMPLE", ignoreCase = true) ||
                (prov?.optBoolean("sample") ?: false) ||
                (prov?.optString("translationService") ?: "").let { it.isEmpty() || !it.contains("/") || it == "ai4bharat/translation" }
            pack.translationService = prov?.optString("translationService", "") ?: ""
            pack.ttsService = prov?.optString("ttsService", "") ?: ""
            pack.platform = prov?.optString("platform", "") ?: ""
            pack.pivot = prov?.optString("pivot", "") ?: ""

            val hr = prov?.optJSONObject("humanReview")
            if (hr != null) {
                pack.humanReview = HumanReview(
                    reviewer = hr.optString("reviewer", ""),
                    background = hr.optString("background", ""),
                    date = hr.optString("date", ""),
                    confirmed = hr.optInt("confirmed", 0),
                    corrected = hr.optInt("corrected", 0),
                    removed = hr.optInt("removed", 0),
                    unreviewed = hr.optInt("unreviewed", 0),
                )
            }

            val entriesObj = root.optJSONObject("entries") ?: JSONObject()
            val keys = entriesObj.keys()
            while (keys.hasNext()) {
                val id = keys.next()
                val e = entriesObj.getJSONObject(id)
                val entry = parseEntry(id, e)
                pack.entries[normaliseKey(entry.source)] = entry
                pack.byId[id] = entry
                val norm = normalise(entry.source)
                if (norm.isNotEmpty()) {
                    pack.normalisedIndex[norm] = entry
                }
            }
            return pack
        }

        /**
         * Read a string field, treating JSON null as absent.
         *
         * org.json returns the literal string "null" from optString when the
         * key holds JSON null rather than returning the default. That made
         * every entry written as {"audio": null} look like it had audio.
         */
        private fun optText(e: JSONObject, key: String): String {
            if (e.isNull(key)) return ""
            return e.optString(key, "")
        }

        private fun parseEntry(id: String, e: JSONObject): PackEntry {
            return PackEntry(
                id = id,
                source = optText(e, "source"),
                target = optText(e, "target"),
                en = optText(e, "en"),
                nipun = optText(e, "nipun"),
                nipunOutcome = optText(e, "nipunOutcome"),
                nipunGoal = optText(e, "nipunGoal"),
                nipunDomain = optText(e, "nipunDomain"),
                kind = optText(e, "kind"),
                service = optText(e, "service"),
                audio = optText(e, "audio").ifEmpty { null },
                audioProvenance = optText(e, "audioProvenance").ifEmpty { null },
                image = optText(e, "image").ifEmpty { null },
                lesson = optText(e, "lesson").ifEmpty { null },
                reviewedBy = optText(e, "reviewedBy"),
                reviewedOn = optText(e, "reviewedOn"),
                reviewVerdict = optText(e, "reviewVerdict"),
                bridge = optText(e, "bridge"),
                bridgeProvenance = optText(e, "bridgeProvenance"),
            )
        }

        /**
         * Normalise a Hindi string for lookup.
         * Trim, collapse whitespace, strip trailing danda/punctuation.
         */
        fun normalise(text: String): String {
            return text.trim()
                .replace(Regex("\\s+"), " ")
                .replace(Regex("[।.?!]+$"), "")
                .trim()
        }

        private fun normaliseKey(text: String): String {
            return text.trim()
        }
    }
}
