package app.olsaathi.content

import android.content.Context
import org.json.JSONObject
import java.util.Locale

/**
 * Loads and queries the pre-translated content pack.
 *
 * The pack is generated by tools/build_pack.mjs and shipped inside the
 * APK as assets/pack/pack.sat.json. Every entry records which Bhashini
 * service produced it, so provenance is in the data.
 *
 * Lookup order:
 *   1. Exact match on source text (trimmed)
 *   2. Normalised match (trim, collapse whitespace, strip trailing ।.?!)
 *   3. UNAVAILABLE
 *
 * N1: There is no generic fallback phrase. A miss returns an empty
 * target with provenance UNAVAILABLE.
 */
class VerifiedContentPack private constructor() {

    data class PackEntry(
        val id: String,
        val source: String,
        val target: String,
        val en: String,
        val nipun: String,
        val kind: String,
        val service: String,
        val audio: String?,
        val lesson: String?,
    )

    // Visible for testing
    /**
     * True when this pack is placeholder content rather than Bhashini output.
     * Every lookup is then downgraded from VERIFIED to SAMPLE, so the app
     * physically cannot present invented Santali as a real translation.
     */
    var isSample: Boolean = false
        private set

    internal val entries = mutableMapOf<String, PackEntry>()
    private val normalisedIndex = mutableMapOf<String, PackEntry>()

    /** Provenance metadata from the pack header. */
    var translationService: String = ""
        private set
    var ttsService: String = ""
        private set
    var platform: String = ""
        private set
    var pivot: String = ""
        private set
    var generated: String = ""
        private set

    /** Number of entries loaded. */
    val size: Int get() = entries.size

    /**
     * Look up by Hindi source text.
     * Returns [Translation] with appropriate provenance.
     */
    fun lookup(hindi: String): Translation {
        val trimmed = hindi.trim()
        if (trimmed.isEmpty()) {
            return Translation(
                source = hindi,
                target = "",
                en = "",
                provenance = Provenance.UNAVAILABLE
            )
        }

        // 1. Exact match
        entries[normaliseKey(trimmed)]?.let { entry ->
            return Translation(
                source = entry.source,
                target = entry.target,
                en = entry.en,
                provenance = if (isSample) Provenance.SAMPLE else Provenance.VERIFIED,
                serviceId = entry.service,
                entryId = entry.id,
                nipun = entry.nipun,
                kind = entry.kind,
            )
        }

        // 2. Normalised match
        val norm = normalise(trimmed)
        normalisedIndex[norm]?.let { entry ->
            return Translation(
                source = entry.source,
                target = entry.target,
                en = entry.en,
                provenance = if (isSample) Provenance.SAMPLE else Provenance.VERIFIED,
                serviceId = entry.service,
                entryId = entry.id,
                nipun = entry.nipun,
                kind = entry.kind,
            )
        }

        // 3. UNAVAILABLE — N1: no fallback, no guess
        return Translation(
            source = hindi,
            target = "",
            en = "",
            provenance = Provenance.UNAVAILABLE
        )
    }

    /** Get the audio asset path for a translation, or null. */
    fun audioPath(translation: Translation): String? {
        return entries[translation.entryId]?.audio
    }

    /** Get all entries, optionally filtered by lesson id. */
    fun entries(lessonId: String? = null): List<PackEntry> {
        return if (lessonId != null) {
            entries.values.filter { it.lesson == lessonId || it.kind == "phrase" }
        } else {
            entries.values.toList()
        }
    }

    /** Get unique lesson IDs from lesson-type entries. */
    fun lessonIds(): List<String> {
        return entries.values
            .filter { it.lesson != null }
            .map { it.lesson!! }
            .distinct()
            .sorted()
    }

    companion object {
        private var instance: VerifiedContentPack? = null

        /** Load the pack from assets. Call once at app startup. */
        fun load(context: Context): VerifiedContentPack {
            instance?.let { return it }

            val pack = VerifiedContentPack()
            val json = context.assets.open("pack/pack.sat.json").bufferedReader(Charsets.UTF_8).use { it.readText() }
            val root = JSONObject(json)

            pack.generated = root.optString("generated", "")
            val prov = root.optJSONObject("provenance")
            // Any of these means the pack was not produced by a real Bhashini
            // run, so nothing in it may claim to be verified.
            pack.isSample = (prov?.optString("note") ?: "").contains("SAMPLE", ignoreCase = true) ||
                (prov?.optBoolean("sample") ?: false) ||
                (prov?.optString("translationService") ?: "").let { it.isEmpty() || !it.contains("/") || it == "ai4bharat/translation" }
            pack.translationService = prov?.optString("translationService", "") ?: ""
            pack.ttsService = prov?.optString("ttsService", "") ?: ""
            pack.platform = prov?.optString("platform", "") ?: ""
            pack.pivot = prov?.optString("pivot", "") ?: ""

            val entriesObj = root.optJSONObject("entries") ?: JSONObject()
            val keys = entriesObj.keys()
            while (keys.hasNext()) {
                val id = keys.next()
                val e = entriesObj.getJSONObject(id)
                val entry = PackEntry(
                    id = id,
                    source = e.optString("source", ""),
                    target = e.optString("target", ""),
                    en = e.optString("en", ""),
                    nipun = e.optString("nipun", ""),
                    kind = e.optString("kind", ""),
                    service = e.optString("service", ""),
                    audio = e.optString("audio", "").ifEmpty { null },
                    lesson = e.optString("lesson", "").ifEmpty { null },
                )
                pack.entries[normaliseKey(entry.source)] = entry
                // Build normalised index for fuzzy lookup
                val norm = normalise(entry.source)
                if (norm.isNotEmpty()) {
                    pack.normalisedIndex[norm] = entry
                }
            }

            instance = pack
            return pack
        }

        /** Visible for testing. */
        internal fun loadFromString(json: String): VerifiedContentPack {
            val pack = VerifiedContentPack()
            val root = JSONObject(json)
            pack.generated = root.optString("generated", "")
            val prov = root.optJSONObject("provenance")
            // Any of these means the pack was not produced by a real Bhashini
            // run, so nothing in it may claim to be verified.
            pack.isSample = (prov?.optString("note") ?: "").contains("SAMPLE", ignoreCase = true) ||
                (prov?.optBoolean("sample") ?: false) ||
                (prov?.optString("translationService") ?: "").let { it.isEmpty() || !it.contains("/") || it == "ai4bharat/translation" }
            pack.translationService = prov?.optString("translationService", "") ?: ""
            pack.ttsService = prov?.optString("ttsService", "") ?: ""
            pack.platform = prov?.optString("platform", "") ?: ""
            pack.pivot = prov?.optString("pivot", "") ?: ""

            val entriesObj = root.optJSONObject("entries") ?: JSONObject()
            val keys = entriesObj.keys()
            while (keys.hasNext()) {
                val id = keys.next()
                val e = entriesObj.getJSONObject(id)
                val entry = PackEntry(
                    id = id,
                    source = e.optString("source", ""),
                    target = e.optString("target", ""),
                    en = e.optString("en", ""),
                    nipun = e.optString("nipun", ""),
                    kind = e.optString("kind", ""),
                    service = e.optString("service", ""),
                    audio = e.optString("audio", "").ifEmpty { null },
                    lesson = e.optString("lesson", "").ifEmpty { null },
                )
                pack.entries[normaliseKey(entry.source)] = entry
                val norm = normalise(entry.source)
                if (norm.isNotEmpty()) {
                    pack.normalisedIndex[norm] = entry
                }
            }
            return pack
        }

        /**
         * Normalise a Hindi string for lookup.
         * Trim, collapse whitespace, strip trailing danda/punctuation.
         */
        fun normalise(text: String): String {
            return text.trim()
                .replace(Regex("\\s+"), " ")
                .replace(Regex("[।.?!]+$"), "")
                .trim()
        }

        private fun normaliseKey(text: String): String {
            return text.trim()
        }
    }
}
